// Package esde holds a translation of ES-DE's system definitions and emulator
// find rules, which between them say what standalone emulator opens a platform
// and where that emulator lives on this OS.
//
// The data is generated by tools/gen-esde from a pinned ES-DE release and
// embedded per OS, so a build carries only the rules it can use. ES-DE is MIT
// licensed; see LICENSE.ES-DE.
package esde

import (
	"encoding/json"
	"fmt"
	"sync"
)

// Alternative is one way to launch a platform, in ES-DE's preference order.
type Alternative struct {
	// Label is ES-DE's own name for the alternative, e.g. "PCSX2 (Standalone)".
	Label string `json:"label"`
	// Emulator keys into Emulators, e.g. "PCSX2".
	Emulator string `json:"emulator"`
	// Args is the argv after the emulator, with %ROM% and friends still in place.
	Args []string `json:"args"`
	// StartDir is the working directory, possibly itself a placeholder.
	StartDir string `json:"start_dir,omitempty"`
}

// FindRule says where an emulator lives: names to look up on PATH, and glob
// patterns to try as absolute paths.
type FindRule struct {
	SystemPath []string `json:"system_path,omitempty"`
	StaticPath []string `json:"static_path,omitempty"`
}

// Data is the generated table for one OS.
type Data struct {
	// Source records the ES-DE release the data was translated from.
	Source string `json:"source"`
	// Systems maps a RomM platform slug to its launch alternatives.
	Systems map[string][]Alternative `json:"systems"`
	// Emulators maps an alternative's Emulator to its discovery rule.
	Emulators map[string]FindRule `json:"emulators"`
}

var (
	once    sync.Once
	loaded  *Data
	loadErr error
)

// Load returns this OS's table, parsing the embedded JSON on first use.
func Load() (*Data, error) {
	once.Do(func() {
		var d Data
		if err := json.Unmarshal(embedded, &d); err != nil {
			loadErr = fmt.Errorf("esde: parsing the embedded table: %w", err)
			return
		}
		loaded = &d
	})
	return loaded, loadErr
}
